spring:
  application:
    name: order-@project.artifactId@
  profiles:
    active: test
  data:
    rest:
      base-path: /api
liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.xml
  enabled: false
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: configserver
#      profile: dev
#      label: master
server:
  port: 9000
info:
  author: dengb
  email: 71290@topscore.com.cn
  app:
    name: @project.groupId@:@project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
---
spring:
  profiles: dev
  datasource:
     url: jdbc:h2:mem:test
     driver-class-name: org.h2.Driver
     username: sa
     password:
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
  thymeleaf:
    cache: false
---
spring:
  profiles: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order?useSSL=true
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  rabbitmq:
    host: 172.16.35.78
    username: guest
    password: guest
---
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-2ze7143bv1kf37lu6o.mysql.rds.aliyuncs.com:3306/orderdb?useUnicode=true&characterEncoding=utf-8
    username: orderuser
    password: Topscore123
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update